name: Terraform Modules CI

on:
  pull_request:

jobs:
  validate:
    name: Validate
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-validate.yaml@main

  lint:
    needs: [validate]
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-lint.yaml@main

  checkov:
    permissions:
      security-events: write
    needs: [validate]
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-checkov.yaml@main

  fmt:
    permissions:
      contents: write
    needs: [lint, checkov]
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-fmt.yaml@main

  docs:
    permissions:
      contents: write
    needs: [lint, checkov]
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-docs.yaml@main
    