name: Terraform Modules CI

on:
  pull_request:

jobs:
  validate:
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-validate.yaml@main

  checkov:
    permissions:
      security-events: write
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-checkov.yaml@main

  docs:
    permissions:
      contents: write
    needs: [validate, checkov]
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-docs.yaml@main