name: Terraform Modules CI

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]
    paths:
      - "**.tf"
      - ".tflint.hcl"
      - "README.md"
  
permissions:
  security-events: write
  contents: write
  pull-requests: write

jobs:
  ci-workflow:
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-ci.yaml@main