name: Terraform Module Release

on:
  push:
    branches:
        - main
  
jobs:
  release:
    permissions:
        contents: write
        pull-requests: write
    name: Release
    uses: joao-zanutto/shared-workflows/.github/workflows/tf-release.yaml@main